name: CI/CD

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  buildntest:
    name: build and test in Node.js and browser
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest]
        node-version: [18, 20, 22.5.1] # 22.5.1 is a temporary fix since 22 now points to 22.5.0 that has a bug that breaks installation
      # When set to true, GitHub cancels all in-progress jobs if any matrix job fails.
      fail-fast: false
      # The maximum number of jobs that can run simultaneously. Set to 1 if you can't run tests in parallel
      # max-parallel: 1
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: install
        run: npm ci
      
      - name: build
        run: npm run build

      - if: matrix.os == 'ubuntu-latest' && matrix.node-version == '22'
        name: browser tests
        run: npm run test:browser-headless
        # env:
        #   VARIABLE1: ${{ secrets.VARIABLE1 }}
        #   VARIABLE2: ${{ secrets.VARIABLE2 }}

      - name: node esm tests
        run: npm run test:node-esm
        # env:
        #   VARIABLE1: ${{ secrets.VARIABLE1 }}
        #   VARIABLE2: ${{ secrets.VARIABLE2 }}
      
      - name: node cjs tests and coverage
        run: npm run coverage
        # env:
        #   VARIABLE1: ${{ secrets.VARIABLE1 }}
        #   VARIABLE2: ${{ secrets.VARIABLE2 }}
