name: Publish to NPM.js

on:
    workflow_run:
        workflows: ['CI/CD']
        types: [completed]
    workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: '22.5.1' # 22.5.1 is a temporary fix since 22 now points to 22.5.0 that has a bug that breaks installation
          registry-url: 'https://registry.npmjs.org'

      - name: install
        run: npm ci
      
      - name: build
        run: npm run build

      - name: coverage
        run: npm run coverage

      - name: send report to coveralls.io
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current package version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: release browser bundles
        uses: softprops/action-gh-release@v2
        with:
          files: |
            LICENSE
            dist/bundles/*.js
          tag_name: v${{ steps.package-version.outputs.current-version }}
          name: "v${{ steps.package-version.outputs.current-version }} browser bundles"

      - name: NPM publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}